version: '3'

tasks:
  default:
    cmds:
      - go build -o tasksamurai ./cmd/tasksamurai
  run:
    cmds:
      - go run ./cmd/tasksamurai
  test:
    cmds:
      - go test ./...
  install-taskwarrior:
    cmds:
      - go install github.com/taskwarrior/taskwarrior@latest
